### ISSUE TITLE
Spurious __MACOSX file inside linux (and probably other) releases

### ISSUE THREAD

**Issue by theolivenbaum** [vot/ffbinaries-prebuilt#16]
We're hitting [an issue](https://github.com/tomaszzmuda/Xabe.FFmpeg/issues/394) with a library that uses this repo to download the official binaries 

Seems like since a few versions, there is a spurious __MACOSX file inside the zip files. 

Any chance they can be removed for new releases?

Example from [v4.4.1](https://github.com/ffbinaries/ffbinaries-prebuilt/releases/download/v4.4.1):

`````bash
$ unzip -l ffmpeg-4.4.1-linux-64.zip 
Archive:  ffmpeg-4.4.1-linux-64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 77173696  10-26-2021 05:06   ffmpeg
      211  10-26-2021 05:06   __MACOSX/._ffmpeg           <<<<< this one!
---------                     -------
 77173907                     2 files
`````

**Comment by theolivenbaum** [comment]
Just saw now the [other issue](https://github.com/ffbinaries/ffbinaries-prebuilt/issues/5), @vot it seems like you can exclude the folders using the zip command like:

````bash
zip -r data.zip . -x ".*" -x "__MACOSX"
````

**Comment by vot** [comment]
Hi @theolivenbaum,
I also got an issue in ffbinaries-node about this being a problem on Windows so it seems like these packages are indeed different from the previous ones somehow.
Probably the ._ffmpeg file is new in the current release. Honestly the whole release prep process has been just right clicking on the binary, clicking "Archive" and naming it appropriately so it's clear which is which :D

I'm repacking all the binaries in this release so that should be resolved in the next 20 minutes or so.

Edit: repackaging is now done :)
Let me know if this issue can be closed now.

**Comment by theolivenbaum** [comment]
Sorry forgot to answer you, but all working perfectly now! Thanks again!
