### ISSUE TITLE
4.2.1 Releases

### ISSUE THREAD

**Issue by tropicoo** [vot/ffbinaries-prebuilt#3]
Hello,
Is there any reason not to publish pre-built ffmpeg 4.2.1 builds?
Thanks.
BR

**Comment by vot** [comment]
Hi @tropicoo,

No reason for that. I generally check ffmpeg.org to see any new release notes.

They post those for major and minor versions only (rather than patch versions) which is why I missed 4.2.1.

I'll get the new release in here shortly (you should be able to use that version at some point next week).

Cheers,
Vot

**Comment by tropicoo** [comment]
Hi. Thank you for clarifying this.

**Comment by vot** [comment]
Hi @tropicoo,

ffmpeg 4.2.1 builds have now been published.
