### ISSUE TITLE
"__MACOSX" folder in ffmpeg win64 binary

### ISSUE THREAD

**Issue by Witchilich** [vot/ffbinaries-prebuilt#5]
I the "__MACOSX" folder inside ffmpeg-4.2.1-win-64.zip intentional ?

**Comment by vot** [comment]
Hi @Restia666Ashdoll, sorry about delayed response.

Simple answer: I decided on zip format because of wide support. **Mac's native zip compression gave me the smallest file sizes.**

As much as the unnecessary folder annoys me, ultimately smaller file size won.
This whole project started out in one weekend shipping just one version of ffmpeg - some of the processes could clearly use improvement :)
I tried to script this task but I couldn't get the results in ~1 hour I initially put into this. I currently do this job manually whenever a new release comes out.

If you could provide a scriptable solution which could package up the files into individual zip files with similar final file size I would love to hear about that.
